macro(FIND_OPTIONAL package_name package_option)
  find_package(${package_name})
  if(${package_name}_FOUND)
    set(ENABLE_${package_name} TRUE)
  else()
    set(ENABLE_${package_name} FALSE)
    if(${package_option})
      message(WARNING "${package_name} not found. Consider disabling")
    endif()
  endif()
endmacro()
